# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  database: cocoon_demo
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000
